apiVersion: v1
entries:
  dpu-networking:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-02-20T14:07:13.436683501+02:00"
    dependencies:
    - condition: multus.enabled
      name: multus
      repository: file://charts/multus
      version: 0.1.0
    - condition: sriov-device-plugin.enabled
      name: sriov-device-plugin
      repository: file://charts/sriov-device-plugin
      version: 0.1.0
    - condition: servicechainset-controller.enabled
      name: servicechainset-controller
      repository: file://charts/servicechainset-controller
      version: 0.1.0
    - condition: nvidia-k8s-ipam.enabled
      name: nvidia-k8s-ipam
      repository: file://charts/nvidia-k8s-ipam
      version: 0.1.0
    - condition: ovs-cni.enabled
      name: ovs-cni
      repository: file://charts/ovs-cni
      version: 0.1.0
    - condition: sfc-controller.enabled
      name: sfc-controller
      repository: file://charts/sfc-controller
      version: 0.1.0
    - condition: flannel.enabled
      name: flannel
      repository: file://charts/flannel
      version: v0.25.1
    - condition: ovs-helper.enabled
      name: ovs-helper
      repository: file://charts/ovs-helper
      version: 0.1.0
    description: A Helm chart for Kubernetes
    digest: 933eeaf8ce6515caf7523d91b63a952f3e82a9ccd040b3632233d03226070778
    name: dpu-networking
    type: application
    urls:
    - https://eranco74.github.io/doca-platform/dpu-networking-0.1.0.tgz
    version: 0.1.0
generated: "2025-02-20T14:07:13.434787859+02:00"
